# Pluck a random handful of SSEN's feeders for all time
So we can analyse some data more easily. We're using SSEN's data because it's the first dataset we got into our production pipeline, so the first one we had a full time range for.

In [2]:
import pandas as pd

Find the random sample from the first month of data. SSEN use the `dataset_id` column as a unique feeder identifier (other DNOs do it differently) so that makes an easy way to find feeders.

In [3]:
feb = pd.read_parquet("s3://weave.energy/data/staging/ssen/2024-02.parquet")
feeders = sorted(feb["dataset_id"].dropna().drop_duplicates().sample(100))
del feb

In [4]:
all_time = pd.read_parquet("s3://weave.energy/data/staging/ssen",
                           columns=["dataset_id", "secondary_substation_id", "secondary_substation_name", "lv_feeder_id", "lv_feeder_name", "aggregated_device_count_active", "total_consumption_active_import", "data_collection_log_timestamp"],
                           filters=[("dataset_id", "in", feeders)],
                           engine="pyarrow")
all_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1184306 entries, 0 to 1184305
Data columns (total 8 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   dataset_id                       1184306 non-null  object
 1   secondary_substation_id          1184306 non-null  object
 2   secondary_substation_name        1184306 non-null  category
 3   lv_feeder_id                     1184306 non-null  object
 4   lv_feeder_name                   1184306 non-null  category
 5   aggregated_device_count_active   1176393 non-null  float64
 6   total_consumption_active_import  1176393 non-null  float64
 7   data_collection_log_timestamp    1184306 non-null  datetime64[ms, UTC]
dtypes: category(2), datetime64[ms, UTC](1), float64(2), object(3)
memory usage: 60.6+ MB

In [5]:
all_time.sort_values(["data_collection_log_timestamp", "dataset_id"], inplace=True)
all_time.to_csv("ssen-10-feeders.csv", index=False)

In [12]:
expected_rows_per_feeder = (all_time["data_collection_log_timestamp"].max() - all_time["data_collection_log_timestamp"].min()).total_seconds() / (30 * 60)
expected_rows_per_feeder

12385.0

In [23]:
with pd.option_context('display.max_rows', 500):
    display(all_time.groupby("dataset_id").agg({"data_collection_log_timestamp": "nunique"}).sort_values(by="data_collection_log_timestamp", ascending=False).reset_index())

      dataset_id  data_collection_log_timestamp
0   551300434005                          12288
1   252600320005                          12288
2   190500324006                          12240
3   551600806503                          12240
4   521800701601                          12240
5   550600347001                          12240
6   610000146005                          12240
7   251800120004                          12240
8   310200107004                          12192
9   400800630001                          12192
10  311900842004                          12192
11  282201602003                          12192
12  252600306003                          12192
13  220501010003                          12192
14  341700407002                          12192
15  370700210002                          12192
16  371600236004                          12192
17  000200800509                          12192
18  401500851003                          12192
19  401700628002                          12192
20  191000226003                          12192
21  491300160001                          12192
22  551700336001                          12192
23  611300505002                          12192
24  642300604004                          12192
25  671601415001                          12192
26  701100310002                          12192
27  701201312502                          12192
28  730500208001                          12192
29  460300312001                          12192
30  340800518001                          12192
31  190501603003                          12192
32  101300422001                          12192
33  007500600802                          12192
34  160600137001                          12192
35  009000507104                          12192
36  045800901505                          12192
37  089000103303                          12192
38  095600402005                          12192
39  100400404002                          12192
40  100700571001                          12192
41  160000308004                          12192
42  101900301002                          12192
43  100900317001                          12192
44  101200126002                          12192
45  431900124003                          12189
46  522200115006                          12144
47  701000116001                          12144
48  191800736001                          12144
49  098600907003                          12144
50  251201306001                          12144
51  027900400309                          12144
52  580100313502                          12144
53  100200712003                          12144
54  611400608001                          12144
55  700800803003                          12144
56  006400201002                          12144
57  491100604001                          12144
58  005801000903                          12144
59  370700212001                          12144
60  342300126501                          12144
61  252800606002                          12144
62  101100412704                          12144
63  310900608004                          12144
64  251700918003                          12144
65  701300402001                          12096
66  701400446001                          12048
67  280300102003                          12048
68  001200703005                          12048
69  100100116001                          12047
70  522500402501                          12000
71  761000104003                          11998
72  701300632002                          11952
73  020900301015                          11950
74  461800712004                          11904
75  098100235301                          11808
76  370800130002                          11760
77  024600363506                          11712
78  160200142002                          11708
79  460301812006                          11664
80  058200719501                          11664
81  091500908004                          11664
82  372500339501                          11568
83  640700713004                          11424
84  520000901003                          11424
85  310500124004                          11376
86  371000617001                          11280
87  401501008001                          11232
88  731600608403                          11232
89  251201204001                          11184
90  401000418003                          11136
91  760100210007                          11040
92  220900807001                          11040
93  522500514002                          11038
94  191960224001                          10411
95  671400428001                          10264
96  002501902507                           9936
97  400500218001                           9215
98  580500547001                           8622
99  252600116001                           6768